permissions:
  contents: write

name: Daily Commit

on:
  schedule:
    - cron: '10 4 * * *'  # Runs daily at 04:10 UTC
  workflow_dispatch:       # ✅ Enables the "Run workflow" button

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f2006005@ds.study.iitm.ac.in - update timestamp
        run: |
          echo "Last run: $(date -u)" > last-run.txt
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "24f2006005@ds.study.iitm.ac.in"
          git add last-run.txt
          git commit -m "Daily commit at $(date -u)"
          git push
